# Generated by Django 5.1.4 on 2024-12-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='atmosphere',
            new_name='color_palettes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='colors',
            new_name='novel_atmo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='genre',
            new_name='novel_genre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='patience',
            new_name='patient',
        ),
    ]
