# Generated by Django 5.1.4 on 2024-12-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_rename_atmosphere_post_color_palettes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color_palettes',
            field=models.JSONField(),
        ),
    ]
